# Generated by Django 5.2.3 on 2025-08-18 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('account_title', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='AI Course Platform', max_length=100)),
                ('platform_email', models.EmailField(default='admin@aicourseplatform.com', max_length=254)),
                ('platform_phone', models.CharField(blank=True, max_length=20)),
                ('easypaisa_instructions', models.TextField(blank=True)),
                ('jazzcash_instructions', models.TextField(blank=True)),
                ('bank_transfer_instructions', models.TextField(blank=True)),
                ('auto_approve_payments', models.BooleanField(default=False)),
                ('auto_approve_amount_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notify_admin_on_payment', models.BooleanField(default=True)),
                ('notify_student_on_approval', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment provider', max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number provided by student', max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('screenshot_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin')),
                ('student_notes', models.TextField(blank=True, help_text='Notes from student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_system.paymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
