# Generated by Django 4.2.7 on 2025-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_account_title',
            field=models.CharField(blank=True, help_text='Bank account title', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='Bank IBAN (if applicable)', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='easypaisa_number',
            field=models.CharField(blank=True, help_text='EasyPaisa account number', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='easypaisa_title',
            field=models.CharField(blank=True, help_text='EasyPaisa account title', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='jazzcash_number',
            field=models.CharField(blank=True, help_text='JazzCash account number', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='jazzcash_title',
            field=models.CharField(blank=True, help_text='JazzCash account title', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_processing_time',
            field=models.CharField(default='24-48 hours', help_text='Expected payment processing time', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='platform_address',
            field=models.TextField(blank=True, help_text='Platform address for bank transfers'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='refund_policy',
            field=models.TextField(blank=True, help_text='Refund policy information'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='support_hours',
            field=models.CharField(default='24/7 Available', help_text='Support hours', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Payment terms and conditions'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp support number', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='auto_approve_amount_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum amount for auto-approval', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='auto_approve_payments',
            field=models.BooleanField(default=False, help_text='Automatically approve payments below the limit'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='bank_transfer_instructions',
            field=models.TextField(blank=True, help_text='Step-by-step instructions for bank transfers'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='easypaisa_instructions',
            field=models.TextField(blank=True, help_text='Step-by-step instructions for EasyPaisa payments'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='jazzcash_instructions',
            field=models.TextField(blank=True, help_text='Step-by-step instructions for JazzCash payments'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='notify_admin_on_payment',
            field=models.BooleanField(default=True, help_text='Send email notification to admin on new payment'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='notify_student_on_approval',
            field=models.BooleanField(default=True, help_text='Send email notification to student on payment approval'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='platform_phone',
            field=models.CharField(default='+92 300 1234567', max_length=20),
        ),
    ]
