# Generated by Django 4.2.7 on 2025-08-19 10:55

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_video_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, help_text='Upload course introduction video (MP4, WebM, AVI, MOV, MKV - Max 500MB)', null=True, upload_to='course_videos/', validators=[courses.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload lesson video file (MP4, WebM, AVI, MOV, MKV - Max 500MB)', null=True, upload_to='lesson_videos/', validators=[courses.models.validate_video_file]),
        ),
    ]
