# Generated by Django 5.2.3 on 2025-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_review_options_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, help_text='When the discount ends', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price during promotion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, help_text='When the discount starts', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discount_active',
            field=models.BooleanField(default=False, help_text='Whether the discount is currently active'),
        ),
    ]
