# Generated by Django 5.2.3 on 2025-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_discount_end_date_course_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Limited Time Offer!', max_length=200)),
                ('description', models.CharField(default='Get amazing discounts on all AI courses', max_length=300)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage (e.g., 50 for 50% off)')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the discount starts (leave blank for immediate start)', null=True)),
                ('end_date', models.DateTimeField(help_text='When the discount expires')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the global discount is currently active')),
                ('show_banner', models.BooleanField(default=True, help_text='Show the discount banner on pages')),
                ('banner_color', models.CharField(choices=[('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')], default='orange', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Discount',
                'verbose_name_plural': 'Global Discounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
