# Generated by Django 5.2.3 on 2025-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_globaldiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AI Course Platform', help_text='Main site name', max_length=100)),
                ('site_tagline', models.CharField(default='Learn AI & Machine Learning', help_text='Site tagline/subtitle', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Site logo (recommended: 200x50px)', null=True, upload_to='site_logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (recommended: 32x32px)', null=True, upload_to='site_favicons/')),
                ('footer_text', models.TextField(default='© 2024 AI Course Platform. All rights reserved.', help_text='Footer copyright text')),
                ('contact_email', models.EmailField(default='contact@aicourseplatform.com', help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', help_text='Contact phone number', max_length=20)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X page URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram page URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', null=True)),
                ('meta_description', models.TextField(default='Learn AI and Machine Learning with our comprehensive online courses. Expert-led tutorials, hands-on projects, and flexible learning paths.', help_text='Meta description for SEO')),
                ('meta_keywords', models.CharField(default='AI, Machine Learning, Python, Data Science, Online Courses', help_text='Meta keywords for SEO', max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (GA4)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
