# Generated by Django 4.2.7 on 2025-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Banner subtitle', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Banner description')),
                ('image', models.ImageField(help_text='Banner image (recommended: 1920x600px)', upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile optimized image (optional)', null=True, upload_to='banners/mobile/')),
                ('animation_type', models.CharField(choices=[('fade', 'Fade In/Out'), ('slide', 'Slide Left/Right'), ('zoom', 'Zoom In/Out'), ('bounce', 'Bounce'), ('flip', 'Flip')], default='fade', help_text='Animation effect for this banner', max_length=50)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promo', 'Promotional Banner'), ('announcement', 'Announcement Banner')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing this banner', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('cta_text', models.CharField(blank=True, help_text='Call to action button text', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Call to action URL', max_length=200)),
                ('cta_color', models.CharField(choices=[('primary', 'Primary Blue'), ('secondary', 'Secondary Gray'), ('success', 'Success Green'), ('danger', 'Danger Red'), ('warning', 'Warning Yellow'), ('info', 'Info Cyan'), ('light', 'Light White'), ('dark', 'Dark Black')], default='primary', help_text='Button color', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
