# Generated by Django 4.2.7 on 2025-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(default='hero', editable=False, max_length=20),
        ),
    ]
