version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=course_platform.settings
    depends_on:
      - db
    networks:
      - ai_course_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ai_course_db
      - POSTGRES_USER=ai_course_user
      - POSTGRES_PASSWORD=ai_course_password
    ports:
      - "5432:5432"
    networks:
      - ai_course_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ai_course_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - ai_course_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  ai_course_network:
    driver: bridge
